
version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    volumes:
    - .:/usr/src/app
    working_dir: /usr/src/app
    #command: nodemon --watch views -e js,ejs app.js
    command: npm run dev
    env_file:
      - .env
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'